
spark-submit --packages mysql:mysql-connector-java:8.0.26,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 --driver-memory 2g --driver-cores 2 --executor-memory 2g --executor-cores 2 --num-executors 2 --conf spark.driver.memoryOverhead=1g --class org.controller.rankingSystemF1.positionPointsMap /home/raptor/IdeaProjects/SparkLearning/build/libs/SparkLearning-1.0-SNAPSHOT.jar outputTopic="recalculate.points" bootStrapServer=localhost:8081,localhost:8082,localhost:8083 valueSerializer="org.apache.kafka.common.serialization.StringSerializer" keySerializer="org.apache.kafka.common.serialization.StringSerializer" checkPointLocation="hdfs://localhost:8020/user/raptor/kafka/pointsRecalc" startingOffsets=latest topic="driver.race.points" schemaName=kafka_db driverPointsTable=driver_points JDBCUrl="jdbc:mysql://localhost:3306/kafka_db?user=raptor?password=" JDBCPassword="" JDBCUser=raptor JDBCDriver="com.mysql.jdbc.Driver" stateExpiry=300000 raceInfoTable=race_info driverInfoTable=driver_info driverRaceInfoTable=driver_race_info driverPointsTemp=driver_point_temp raceTrackInfoTable=race_track_info pointsPositionMapTable=points_position_map driverStandingsTable=driver_standings inputPath="hdfs://localhost:8020/user/raptor/inputBatchPointsPositionMap/file1.txt"

spark-submit --packages mysql:mysql-connector-java:8.0.26,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 --driver-memory 2g --driver-cores 2 --executor-memory 2g --executor-cores 2 --num-executors 2 --conf spark.driver.memoryOverhead=1g --class org.controller.rankingSystemF1.positionPointsMap /home/raptor/IdeaProjects/SparkLearning/build/libs/SparkLearning-1.0-SNAPSHOT.jar outputTopic="recalculate.points" bootStrapServer=localhost:8081,localhost:8082,localhost:8083 valueSerializer="org.apache.kafka.common.serialization.StringSerializer" keySerializer="org.apache.kafka.common.serialization.StringSerializer" checkPointLocation="hdfs://localhost:8020/user/raptor/kafka/pointsRecalc" startingOffsets=latest topic="driver.race.points" schemaName=kafka_db driverPointsTable=driver_points JDBCUrl="jdbc:mysql://localhost:3306/kafka_db?user=raptor?password=" JDBCPassword="" JDBCUser=raptor JDBCDriver="com.mysql.jdbc.Driver" stateExpiry=300000 raceInfoTable=race_info driverInfoTable=driver_info driverRaceInfoTable=driver_race_info driverPointsTemp=driver_point_temp raceTrackInfoTable=race_track_info pointsPositionMapTable=points_position_map driverStandingsTable=driver_standings inputPath="hdfs://localhost:8020/user/raptor/inputBatchPointsPositionMap/file2.txt"

spark-submit --packages mysql:mysql-connector-java:8.0.26,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 --driver-memory 2g --driver-cores 2 --executor-memory 2g --executor-cores 2 --num-executors 2 --conf spark.driver.memoryOverhead=1g --class org.controller.rankingSystemF1.positionPointsMap /home/raptor/IdeaProjects/SparkLearning/build/libs/SparkLearning-1.0-SNAPSHOT.jar outputTopic="recalculate.points" bootStrapServer=localhost:8081,localhost:8082,localhost:8083 valueSerializer="org.apache.kafka.common.serialization.StringSerializer" keySerializer="org.apache.kafka.common.serialization.StringSerializer" checkPointLocation="hdfs://localhost:8020/user/raptor/kafka/pointsRecalc" startingOffsets=latest topic="driver.race.points" schemaName=kafka_db driverPointsTable=driver_points JDBCUrl="jdbc:mysql://localhost:3306/kafka_db?user=raptor?password=" JDBCPassword="" JDBCUser=raptor JDBCDriver="com.mysql.jdbc.Driver" stateExpiry=300000 raceInfoTable=race_info driverInfoTable=driver_info driverRaceInfoTable=driver_race_info driverPointsTemp=driver_point_temp raceTrackInfoTable=race_track_info pointsPositionMapTable=points_position_map driverStandingsTable=driver_standings inputPath="hdfs://localhost:8020/user/raptor/inputBatchPointsPositionMap/file3.txt"

spark-submit --packages mysql:mysql-connector-java:8.0.26,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 --driver-memory 2g --driver-cores 2 --executor-memory 2g --executor-cores 2 --num-executors 2 --conf spark.driver.memoryOverhead=1g --class org.controller.rankingSystemF1.positionPointsMap /home/raptor/IdeaProjects/SparkLearning/build/libs/SparkLearning-1.0-SNAPSHOT.jar outputTopic="recalculate.points" bootStrapServer=localhost:8081,localhost:8082,localhost:8083 valueSerializer="org.apache.kafka.common.serialization.StringSerializer" keySerializer="org.apache.kafka.common.serialization.StringSerializer" checkPointLocation="hdfs://localhost:8020/user/raptor/kafka/pointsRecalc" startingOffsets=latest topic="driver.race.points" schemaName=kafka_db driverPointsTable=driver_points JDBCUrl="jdbc:mysql://localhost:3306/kafka_db?user=raptor?password=" JDBCPassword="" JDBCUser=raptor JDBCDriver="com.mysql.jdbc.Driver" stateExpiry=300000 raceInfoTable=race_info driverInfoTable=driver_info driverRaceInfoTable=driver_race_info driverPointsTemp=driver_point_temp raceTrackInfoTable=race_track_info pointsPositionMapTable=points_position_map driverStandingsTable=driver_standings inputPath="hdfs://localhost:8020/user/raptor/inputBatchPointsPositionMap/file4.txt"

mysql -u raptor -e "update kafka_db.points_position_map set end_date='2020-05-01' where season=2020 and position=2 and start_date='2020-02-01'"

spark-submit --packages mysql:mysql-connector-java:8.0.26,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 --driver-memory 2g --driver-cores 2 --executor-memory 2g --executor-cores 2 --num-executors 2 --conf spark.driver.memoryOverhead=1g --class org.controller.rankingSystemF1.positionPointsMap /home/raptor/IdeaProjects/SparkLearning/build/libs/SparkLearning-1.0-SNAPSHOT.jar outputTopic="recalculate.points" bootStrapServer=localhost:8081,localhost:8082,localhost:8083 valueSerializer="org.apache.kafka.common.serialization.StringSerializer" keySerializer="org.apache.kafka.common.serialization.StringSerializer" checkPointLocation="hdfs://localhost:8020/user/raptor/kafka/pointsRecalc" startingOffsets=latest topic="driver.race.points" schemaName=kafka_db driverPointsTable=driver_points JDBCUrl="jdbc:mysql://localhost:3306/kafka_db?user=raptor?password=" JDBCPassword="" JDBCUser=raptor JDBCDriver="com.mysql.jdbc.Driver" stateExpiry=300000 raceInfoTable=race_info driverInfoTable=driver_info driverRaceInfoTable=driver_race_info driverPointsTemp=driver_point_temp raceTrackInfoTable=race_track_info pointsPositionMapTable=points_position_map driverStandingsTable=driver_standings inputPath="hdfs://localhost:8020/user/raptor/inputBatchPointsPositionMap/file5.txt"

mysql -u raptor -e "update kafka_db.points_position_map set end_date='2020-05-01' where season=2020 and position=3 and start_date='2020-02-01'"

spark-submit --packages mysql:mysql-connector-java:8.0.26,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 --driver-memory 2g --driver-cores 2 --executor-memory 2g --executor-cores 2 --num-executors 2 --conf spark.driver.memoryOverhead=1g --class org.controller.rankingSystemF1.positionPointsMap /home/raptor/IdeaProjects/SparkLearning/build/libs/SparkLearning-1.0-SNAPSHOT.jar outputTopic="recalculate.points" bootStrapServer=localhost:8081,localhost:8082,localhost:8083 valueSerializer="org.apache.kafka.common.serialization.StringSerializer" keySerializer="org.apache.kafka.common.serialization.StringSerializer" checkPointLocation="hdfs://localhost:8020/user/raptor/kafka/pointsRecalc" startingOffsets=latest topic="driver.race.points" schemaName=kafka_db driverPointsTable=driver_points JDBCUrl="jdbc:mysql://localhost:3306/kafka_db?user=raptor?password=" JDBCPassword="" JDBCUser=raptor JDBCDriver="com.mysql.jdbc.Driver" stateExpiry=300000 raceInfoTable=race_info driverInfoTable=driver_info driverRaceInfoTable=driver_race_info driverPointsTemp=driver_point_temp raceTrackInfoTable=race_track_info pointsPositionMapTable=points_position_map driverStandingsTable=driver_standings inputPath="hdfs://localhost:8020/user/raptor/inputBatchPointsPositionMap/file6.txt"

mysql -u raptor -e "update kafka_db.points_position_map set end_date='2020-05-01' where season=2020 and position=4 and start_date='2020-01-01'"

spark-submit --packages mysql:mysql-connector-java:8.0.26,org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.2 --driver-memory 2g --driver-cores 2 --executor-memory 2g --executor-cores 2 --num-executors 2 --conf spark.driver.memoryOverhead=1g --class org.controller.rankingSystemF1.positionPointsMap /home/raptor/IdeaProjects/SparkLearning/build/libs/SparkLearning-1.0-SNAPSHOT.jar outputTopic="recalculate.points" bootStrapServer=localhost:8081,localhost:8082,localhost:8083 valueSerializer="org.apache.kafka.common.serialization.StringSerializer" keySerializer="org.apache.kafka.common.serialization.StringSerializer" checkPointLocation="hdfs://localhost:8020/user/raptor/kafka/pointsRecalc" startingOffsets=latest topic="driver.race.points" schemaName=kafka_db driverPointsTable=driver_points JDBCUrl="jdbc:mysql://localhost:3306/kafka_db?user=raptor?password=" JDBCPassword="" JDBCUser=raptor JDBCDriver="com.mysql.jdbc.Driver" stateExpiry=300000 raceInfoTable=race_info driverInfoTable=driver_info driverRaceInfoTable=driver_race_info driverPointsTemp=driver_point_temp raceTrackInfoTable=race_track_info pointsPositionMapTable=points_position_map driverStandingsTable=driver_standings inputPath="hdfs://localhost:8020/user/raptor/inputBatchPointsPositionMap/file7.txt"

