# ngnix-service-loadbalancer.yaml
apiVersion: v1
kind: Service
metadata:
    name: nginx-service-loadbalancer
    # label not required for RC unlesss if it's being reffered somewhere else.
    labels:
         app: nginx_service_loadbalancer  #this spec is used in selector
         tier: service
         environment: dev
spec:
    type: LoadBalancer
    ports:
    - nodePort: 31000
      port: 80
      targetPort: 80 # containerPort of the container in pod which is running
    # set based selector, can be used to select multiple options in single selection
    selector:  # set based selectors are only vailable in apps/v1 type
    #  matchLabels:
        app: nginx
    #  matchExpressions:  
    #   - {key: environment, operator: In, values: [dev]}
    #   - {key: tier, operator: NotIn, values: [frontend,backend]}