# pod-hostPath-example.yaml
apiVersion: v1
kind: Pod
metadata:
    name: pod-host-path
    # label not required for RC unlesss if it's being reffered somewhere else.
    labels:
         app: pod_host_path  #this spec is used in selector
         tier: service
         environment: dev
spec:
    containers:
    -   name: redis-container   
        image : redis
        volumeMounts:
        - mountPath: /test-vol     # this is the directory name inside the pod
          name: test-volume     #    <--|  used here
    volumes:                    #       |
    -   name: test-volume       #    ---|  this name is 
        hostPath :
          path: /d/files/        
          #path: /c/Users         # thisis the path of c users that is mounted to minikube VM , got it from minikube shell