# pod-secrets-environment-example.yaml  
apiVersion: v1
kind: Pod
metadata:
    name: pod-secrets-environment
    # label not required for RC unlesss if it's being reffered somewhere else.
    labels:
         app: pod_secrets_environment  #this spec is used in selector
         tier: service
         environment: dev
spec:
    containers:
    - name: redis
      image: redis
      env :
        - name: user_name
          valueFrom :
            secretKeyRef :
              name: my-secret # name of string literal config
              key: username # key for the config properties
        - name: pass_word
          valueFrom :
            secretKeyRef :
              name: my-secret # name of string literal config   , We can use different configmap name here if it's from different configmap
              key: password # key for the config properties
    restartPolicy: Never
      
