# redis-slave-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis-slave-service-deployment
    # label not required for RC unlesss if it's being reffered somewhere else.
    labels:
         app: redis_slave_deployment  #this spec is used in selector
         tier: backend
         role: slave
         environment: dev
spec:
    replicas: 2
    selector: # set based selector, can be used to select multiple options in single selection
      matchLabels:
        app: redis                                                          #  <----
      matchExpressions:                                                     #      |
        - {key: environment, operator: In, values: [dev]}                   #      |
        - {key: tier, operator: NotIn, values: [frontend,service]}          #      |
    template :                                                              #      |
        metadata:                                                           #      |
            name: redis                                                     #      |
            labels:                                                         #      |
                app: redis  #this spec is used in selector                  #  ----- (pod label)
                tier: backend
                role: slave
                environment : dev
        spec:
            containers:
            -   name: slave                                       # container inside Pod   ,we can have multiple container inside pod
                image : gcr.io/google_samples/gb-redisslave:v1
                resources:
                  requests:
                    cpu: 100m
                    memory: 100Mi
                ports:
                -   containerPort: 6379   